DROP TABLE IF EXISTS rg_sound;

CREATE TABLE rg_sound (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data INTEGER NOT NULL,
  sample_time INTEGER NOT NULL,
  sample_date INTEGER NOT NULL
);
